spring.application.name=OrderService

server.port=8080
kite.api.key=43nvp9vy5thwo67h
kite.api.secret=mehj5f7q72pq16irwdrg619zginvzgi0
kite.redirect.uri=http://localhost:8080/kite-callback


# Increase logging to DEBUG for your application package
logging.level.com.personal.algo=DEBUG

# Keep Spring at INFO to avoid too much noise
logging.level.org.springframework=DEBUG

# Optional: enable verbose HTTP client logs (helpful for HttpClient issues)
logging.level.org.apache.http=DEBUG
